export const USER_ORDER = "USER_ORDER";
// HOME SLIDER BANNER
export const HOME_SLIDER_BANNER = "HOME_SLIDER_BANNER";
// BEST SALE FROM HOME
export const HOME_BESAT_SALE = "HOME_BESAT_SALE";
// SPECIAL OFFER
export const SPECIAL_OFFER_ITEMS = "SPECIAL_OFFER_ITEMS";
// SALES-FILTER
export const SALES_FILTER_LOGIC = "SALES_FILTER_LOGIC";
