export const buyserData = [
    {
        id: 1,
        categoryType: 'Բույսեր',
        categoryTypeSales: 'Բույսեր',
        categoryName: 'Ֆալենոպսիս',
        categoryNameSales: 'Ֆալենոպսիս',
        productimg: 'https://abio.am/image/cache/catalog/000002/img_20200621_104012-270x316.jpg',
        price: 1,
        productName: 'Ֆալենոպսիս Elegant 206',
        zexcher: '25%',
        quantity: 1
    },
    {
        id: 2,
        categoryType: 'Բույսեր',
        categoryTypeSales: 'Բույսեր',
        categoryName: 'Ֆալենոպսիս',
        categoryNameSales: 'Ֆալենոպսիս',
        productimg: 'https://abio.am/image/cache/catalog/000002/img_20200621_103850-270x316.jpg',
        price: 3245,
        productName: 'ԽՈԼՈՐՁ 2 ՃՅՈՒՂ',
        arkaChe: 'ԱՌԿԱ ՉԷ',
        quantity: 1
    },
    {
        id: 3,
        categoryType: 'Բույսեր',
        categoryTypeSales: 'Բույսեր',
        categoryName: 'Սենյակային բույսեր',
        categoryNameSales: 'Սենյակային բույսեր',
        productimg: 'https://abio.am/image/cache/catalog/000002/5%2B%2B6415451-270x316.jpg',
        price: 5,
        productName: 'Ալոե Վերա',
        quantity: 1
    },
    {
        id: 4,
        categoryType: 'Բույսեր',
        categoryTypeSales: 'Բույսեր',
        categoryName: 'Սենյակային բույսեր',
        categoryNameSales: 'Սենյակային բույսեր',
        productimg: 'https://abio.am/image/cache/catalog/falik/anthuriumroyalchampion-270x316.jpg',
        price: 255,
        productName: 'Անթուրիում Andr. 17-65',
        quantity: 1
    },
    {
        id: 5,
        categoryType: 'Բույսեր',
        categoryTypeSales: 'Բույսեր',
        categoryName: 'Սենյակային բույսեր',
        categoryNameSales: 'Սենյակային բույսեր',
        productimg: 'https://abio.am/image/cache/catalog/0001/13333/img_20200825_132939-270x316.jpg',
        price: 15,
        productName: 'Ասպլենիում Նիդուս',
        quantity: 1
    },
    {
        id: 6,
        categoryType: 'Բույսեր',
        categoryTypeSales: 'Բույսեր',
        categoryName: 'Այգու բույսեր',
        categoryNameSales: 'Այգու բույսեր',
        productimg: 'https://abio.am/image/cache/catalog/0000/0-02-05-93114dae6cad99ba2b98a0c5f9e3262f0061d62e837c0e160373800b438a21a8_c463713e5102bdd0-270x316.jpg',
        price: 4500,
        productName: 'Եղևնի',
        quantity: 1
    },
    {
        id: 7,
        categoryType: 'Բույսեր',
        categoryTypeSales: 'Բույսեր',
        categoryName: 'Այգու բույսեր',
        categoryNameSales: 'Այգու բույսեր',
        productimg: 'https://abio.am/image/cache/catalog/falik/buxus-sempervirens-270x316.png',
        price: 2500,
        productName: 'Բուքսուս',
        quantity: 1
    },
    {
        id: 8,
        categoryType: 'Բույսեր',
        categoryTypeSales: 'Բույսեր',
        categoryName: 'Տնկիներ',
        categoryNameSales: 'Տնկիներ',
        productimg: 'https://abio.am/image/cache/catalog/sazhency/samshit-270x316.jpg',
        price: 1000,
        productName: 'Սամշիտ Փոքր',
        quantity: 1
    },
    {
        id: 9,
        categoryType: 'Բույսեր',
        categoryTypeSales: 'Բույսեր',
        categoryName: 'Տնկիներ',
        categoryNameSales: 'Տնկիներ',
        productimg: 'https://abio.am/image/cache/catalog/sazhency/roza_chajno-gibridnaja_zheltaja-270x316.jpg',
        price: 10000,
        productName: 'Վարդ 4',
        quantity: 1
    },
    {
        id: 10,
        categoryType: 'Բույսեր',
        categoryTypeSales: 'Բույսեր',
        categoryName: 'Սերմեր',
        categoryNameSales: 'Սերմեր',
        productimg: 'https://abio.am/image/cache/catalog/00003/5a3654d73cebc_vetnoy_fontan_01g_avrish_909_rub.-270x316.jpg',
        price: 5600,
        productName: 'Սերմ- Ֆլոկս Ցվետնոյ',
        quantity: 1
    },
    {
        id: 11,
        categoryType: 'Բույսեր',
        categoryTypeSales: 'Բույսեր',
        categoryName: 'Սերմեր',
        categoryNameSales: 'Սերմեր',
        productimg: 'https://abio.am/image/cache/catalog/00003/145047704_787497485306916_8126127779770513297_n%281%29-270x316.jpg',
        price: 6000,
        productName: 'Սերմ-Լիմոնիում Սմես',
        quantity: 1
    },
    {
        id: 12,
        categoryType: 'Հողախառնուրդներ, պարարտանյութեր',
        categoryTypeSales: 'Հողախառնուրդներ, պարարտանյութեր',
        categoryName: 'Հողախառնուրդներ',
        categoryNameSales: 'Հողախառնուրդներ',
        productimg: 'https://abio.am/image/cache/catalog/000002/img_20200615_110934-270x316.jpg',
        price: 3000,
        productName: 'Դրենաժ 2լ',
        quantity: 1
    },
    {
        id: 13,
        categoryType: 'Հողախառնուրդներ, պարարտանյութեր',
        categoryTypeSales: 'Հողախառնուրդներ, պարարտանյութեր',
        categoryName: 'Հողախառնուրդներ',
        categoryNameSales: 'Հողախառնուրդներ',
        productimg: 'https://abio.am/image/cache/catalog/000002/fxxgjdgjfh-270x316.jpg',
        price: 12000,
        productName: 'Հանքանյին Սուբստրատ 5լ',
        quantity: 1
    },
    {
        id: 14,
        categoryType: 'Հողախառնուրդներ, պարարտանյութեր',
        categoryTypeSales: 'Հողախառնուրդներ, պարարտանյութեր',
        categoryName: 'Պարարտանյութեր',
        categoryNameSales: 'Պարարտանյութեր',
        productimg: 'https://abio.am/image/cache/catalog/0000/fertilizers/2130081-270x316.jpg',
        price: 15000,
        productName: 'Ագրիկոլա Վարդի',
        quantity: 1
    },
    {
        id: 15,
        categoryType: 'Հողախառնուրդներ, պարարտանյութեր',
        categoryTypeSales: 'Հողախառնուրդներ, պարարտանյութեր',
        categoryName: 'Պարարտանյութեր',
        categoryNameSales: 'Պարարտանյութեր',
        productimg: 'https://abio.am/image/cache/catalog/0000/fertilizers/213190916-270x316.jpg',
        price: 45000,
        productName: 'Ագրիկոլա Օրխիդեա 25գ',
        quantity: 1
    },
    {
        id: 16,
        categoryType: 'Հողախառնուրդներ, պարարտանյութեր',
        categoryTypeSales: 'Հողախառնուրդներ, պարարտանյութեր',
        categoryName: 'Թունաքիմիկատներ',
        categoryNameSales: 'Թունաքիմիկատներ',
        productimg: 'https://abio.am/image/cache/catalog/compositions/54354-270x316.jpg',
        price: 8500,
        productName: 'Ծառերի Ներկանյութ 5լ',
        quantity: 1
    },
    {
        id: 17,
        categoryType: 'Հողախառնուրդներ, պարարտանյութեր',
        categoryTypeSales: 'Հողախառնուրդներ, պարարտանյութեր',
        categoryName: 'Թունաքիմիկատներ',
        categoryNameSales: 'Թունաքիմիկատներ',
        productimg: 'https://abio.am/image/cache/catalog/fertilizers/agrikola_fertilizer_4_conifers-270x316.jpg',
        price: 65200,
        productName: 'Ագրիկոլա Փշատերևի Համար 250մլ',
        quantity: 1
    },
    {
        id: 18,
        categoryType: 'Հողախառնուրդներ, պարարտանյութեր',
        categoryTypeSales: 'Հողախառնուրդներ, պարարտանյութեր',
        categoryName: 'Բնական, բուսական օրգանական միջոցներ',
        categoryNameSales: 'Բնական, բուսական օրգանական միջոցներ',
        productimg: 'https://abio.am/image/cache/catalog/fertilizers/bio_antisnake_1-270x316.jpg',
        price: 8500,
        productName: 'Օձերի Դեմ Միջոց 100գ',
        quantity: 1
    },
    {
        id: 19,
        categoryType: 'Ծաղկամաններ',
        categoryTypeSales: 'Ծաղկամաններ',
        categoryName: 'Պլաստմասե ծաղկամաններ',
        categoryNameSales: 'Պլաստմասե ծաղկամաններ',
        productimg: 'https://abio.am/image/cache/catalog/0001/8888/img_20200726_094532-270x316.jpg',
        price: 9000,
        productName: 'Եղևնի Փոքր',
        quantity: 1
    },
    {
        id: 20,
        categoryType: 'Ծաղկամաններ',
        categoryTypeSales: 'Ծաղկամաններ',
        categoryName: 'Պլաստմասե ծաղկամաններ',
        categoryNameSales: 'Պլաստմասե ծաղկամաններ',
        productimg: 'https://abio.am/image/cache/catalog/0000/pots/1702921_1-270x316.jpg',
        price: 75000,
        productName: 'Ծաղկ. Օրխ. 15|17սմ Թափ.',
        quantity: 1
    },
    {
        id: 21,
        categoryType: 'Ծաղկամաններ',
        categoryTypeSales: 'Ծաղկամաններ',
        categoryName: 'Կերամիկական ծաղկամաններ',
        categoryNameSales: 'Կերամիկական ծաղկամաններ',
        productimg: 'https://abio.am/image/cache/catalog/0000/pots/1703011-270x316.jpg',
        price: 7500,
        productName: 'Կավե Աման',
        quantity: 1
    },
    {
        id: 22,
        categoryType: 'Ծաղկամաններ',
        categoryTypeSales: 'Ծաղկամաններ',
        categoryName: 'Կերամիկական ծաղկամաններ',
        categoryNameSales: 'Կերամիկական ծաղկամաններ',
        productimg: 'https://abio.am/image/cache/catalog/0000/pots/1703019-270x316.jpg',
        price: 25000,
        productName: 'Կավե Աման Մեղր',
        quantity: 1
    },
    {
        id: 23,
        categoryType: 'Ծաղկամաններ',
        categoryTypeSales: 'Ծաղկամաններ',
        categoryName: 'Գիպսոբետոնե ծաղկամաններ',
        categoryNameSales: 'Գիպսոբետոնե ծաղկամաններ',
        productimg: 'https://abio.am/image/cache/catalog/0001/33333/img_20200708_172800-270x316.jpg',
        price: 7500,
        productName: 'ԲԵՏՈՆԵ ԾԱՂԿԱՄԱՆ ALD',
        quantity: 1
    },
    {
        id: 24,
        categoryType: 'Ծաղկամաններ',
        categoryTypeSales: 'Ծաղկամաններ',
        categoryName: 'Ֆիբրե ծաղկամաններ',
        categoryNameSales: 'Ֆիբրե ծաղկամաններ',
        productimg: 'https://abio.am/image/cache/catalog/falik/20tram11barc836hat-270x316.jpg',
        price: 5000,
        productName: 'Կերամ. Ծաղկ. 9301-2',
        quantity: 1
    },
    {
        id: 25,
        categoryType: 'Ծաղկամաններ',
        categoryTypeSales: 'Ծաղկամաններ',
        categoryName: 'Փայտյա կաշպոներ',
        categoryNameSales: 'Փայտյա կաշպոներ',
        productimg: 'https://abio.am/image/cache/catalog/0000/img_20210804_104205-270x316.jpg',
        price: 4500,
        productName: 'Դեկ. Փայտ. Ծաղկ. GH9118',
        quantity: 1
    },
    {
        id: 26,
        categoryType: 'Ծաղկամաններ',
        categoryTypeSales: 'Ծաղկամաններ',
        categoryName: 'Փայտյա կաշպոներ',
        categoryNameSales: 'Փայտյա կաշպոներ',
        productimg: 'https://abio.am/image/cache/catalog/0001/55555/img_20200912_101244-270x316.jpg',
        price: 8400,
        productName: 'Դեկ. Փայտե Ծաղկ. GH9387',
        quantity: 1
    },
    {
        id: 27,
        categoryType: 'Ծաղկամաններ',
        categoryTypeSales: 'Ծաղկամաններ',
        categoryName: 'Ծղոտե կաշպոներ',
        categoryNameSales: 'Ծղոտե կաշպոներ',
        productimg: 'https://abio.am/image/cache/catalog/korzina/12-270x316.jpg',
        price: 6000,
        productName: '158.2 Դեկորատիվ Պարագա',
        quantity: 1
    },
    {
        id: 28,
        categoryType: 'Ծաղկամաններ',
        categoryTypeSales: 'Ծաղկամաններ',
        categoryName: 'Ծղոտե կաշպոներ',
        categoryNameSales: 'Ծղոտե կաշպոներ',
        productimg: 'https://abio.am/image/cache/catalog/0000/img_20210804_121022-270x316.jpg',
        price: 98000,
        productName: 'Զամբյուղ A3-2|2',
        quantity: 1
    },
    {
        id: 29,
        categoryType: 'Այգու գործիքներ',
        categoryTypeSales: 'Այգու գործիքներ',
        categoryName: 'Այգեգործական գործիքներ',
        categoryNameSales: 'Այգեգործական գործիքներ',
        productimg: 'https://abio.am/image/cache/catalog/123/9999999/kayqinkarner/photoroom-20211123_161933-270x316.png',
        price: 35000,
        productName: 'ՁԵՌԿԻ ԽՈՏՀՆՁԻՉ ԲԵՆԶԻՆ',
        quantity: 1
    },
    {
        id: 30,
        categoryType: 'Այգու գործիքներ',
        categoryTypeSales: 'Այգու գործիքներ',
        categoryName: 'Հագուստ',
        categoryNameSales: 'Հագուստ',
        productimg: 'https://abio.am/image/cache/catalog/banner/tools/img_20190627_140121-270x316.jpg',
        price: 13300,
        productName: '138 Ռետինե Սապոկ',
        quantity: 1
    },
    //Կահույք և դեկոր
    {
        id: 31,
        categoryType: 'Կահույք և դեկոր',
        categoryTypeSales: 'Կահույք և դեկոր',
        categoryName: 'Ամառանոցային կահույք',
        categoryNameSales: 'Ամառանոցային կահույք',
        productimg: 'https://abio.am/image/cache/catalog/gardenfurniture/11-270x316.jpg',
        price: 45000,
        productName: '149 Պարտեզային Կահույք',
        quantity: 1
    },
    {
        id: 32,
        categoryType: 'Կահույք և դեկոր',
        categoryTypeSales: 'Կահույք և դեկոր',
        categoryName: 'Տաղավարներ',
        categoryNameSales: 'Տաղավարներ',
        productimg: 'https://abio.am/image/cache/catalog/besedka/folding-red-gazebo-3x3-garden-terrace-270x316.jpg',
        price: 65000,
        productName: 'Կտորից Տաղավար (Կարմիր)',
        quantity: 1
    },
    {
        id: 33,
        categoryType: 'Կահույք և դեկոր',
        categoryTypeSales: 'Կահույք և դեկոր',
        categoryName: 'Փայտյա պահարան',
        categoryNameSales: 'Փայտյա պահարան',
        productimg: 'https://abio.am/image/cache/catalog/0001/11111/img_20200702_180348-270x316.jpg',
        price: 4500,
        productName: 'Արդուկի Սեղան Դարակով',
        quantity: 1
    },
    {
        id: 34,
        categoryType: 'Կահույք և դեկոր',
        categoryTypeSales: 'Կահույք և դեկոր',
        categoryName: 'Զարդատուփ',
        categoryNameSales: 'Զարդատուփ',
        productimg: 'https://abio.am/image/cache/catalog/0001/img_20210321_104953%2B1%2B%2B%2B%2B-270x316.jpg',
        price: 4500,
        productName: '127.2 Զարդատուփ Արհ. Կաշվեպատ',
        quantity: 1
    },
    {
        id: 35,
        categoryType: 'Կահույք և դեկոր',
        categoryTypeSales: 'Կահույք և դեկոր',
        categoryName: 'Ֆիբրե դեկոր',
        categoryNameSales: 'Ֆիբրե դեկոր',
        productimg: 'https://abio.am/image/cache/catalog/falik/13barc35erk35-270x316.jpg',
        price: 35000,
        productName: 'ԱՐՁԱՆԻԿ',
        quantity: 1
    },
    {
        id: 36,
        categoryType: 'Կահույք և դեկոր',
        categoryTypeSales: 'Կահույք և դեկոր',
        categoryName: 'Մետաղյա դեկոր',
        categoryNameSales: 'Մետաղյա դեկոր',
        productimg: 'https://abio.am/image/cache/catalog/00001/img_20200807_103622-270x316.jpg',
        price: 7500,
        productName: '129 Դեկորատիվ Պարագա',
        quantity: 1
    },
    {
        id: 37,
        categoryType: 'Կահույք և դեկոր',
        categoryTypeSales: 'Կահույք և դեկոր',
        categoryName: 'Փայտյա դեկոր',
        categoryNameSales: 'Փայտյա դեկոր',
        productimg: 'https://abio.am/image/cache/catalog/marine/shelf1big-270x316.jpg',
        price: 15000,
        productName: 'Փայտե Շրջանակով Հայելի',
        quantity: 1
    },
    {
        id: 38,
        categoryType: 'Կահույք և դեկոր',
        categoryTypeSales: 'Կահույք և դեկոր',
        categoryName: 'Ծղոտե դեկոր',
        categoryNameSales: 'Ծղոտե դեկոր',
        productimg: 'https://abio.am/image/cache/catalog/forniture/38-270x316.jpg',
        price: 1000,
        productName: '84.4 Ծղոտից Զամբյուղ',
        quantity: 1
    },
    {
        id: 39,
        categoryType: 'Կահույք և դեկոր',
        categoryTypeSales: 'Կահույք և դեկոր',
        categoryName: 'Ապակե դեկոր',
        categoryNameSales: 'Ապակե դեկոր',
        productimg: 'https://abio.am/image/cache/catalog/050919/img_3355-270x316.jpg',
        price: 85000,
        productName: '234 Պատի Ժամացույցներ',
        quantity: 1
    },
    {
        id: 40,
        categoryType: 'Կահույք և դեկոր',
        categoryTypeSales: 'Կահույք և դեկոր',
        categoryName: 'Արհեստական դեկոր',
        categoryNameSales: 'Արհեստական դեկոր',
        productimg: 'https://abio.am/image/cache/catalog/0000/244714120_235864871851784_50944066002327935_n-270x316.jpg',
        price: 45000,
        productName: 'Փայտե Ցանկ. 25*35 A1-10',
        quantity: 1
    },
    {
        id: 41,
        categoryType: 'Կահույք և դեկոր',
        categoryTypeSales: 'Կահույք և դեկոր',
        categoryName: 'Ամանորյա դեկոր',
        categoryNameSales: 'Ամանորյա դեկոր',
        productimg: 'https://abio.am/image/cache/catalog/4-270x316.jpg',
        price: 15000,
        productName: '203 Ապակյա Դեկ. Պարագաներ',
        quantity: 1
    },
    {
        id: 42,
        categoryType: 'Պիկնիկի համար',
        categoryTypeSales: 'Պիկնիկի համար',
        categoryName: 'Պիկնիկի պարագաներ',
        categoryNameSales: 'Պիկնիկի պարագաներ',
        productimg: 'https://abio.am/image/cache/catalog/picnic/m14-270x316.jpg',
        price: 40000,
        productName: 'Ածուխով Մանղալ A28-5',
        quantity: 1
    },
    {
        id: 43,
        categoryType: 'Պիկնիկի համար',
        categoryTypeSales: 'Պիկնիկի համար',
        categoryName: 'Տուփ',
        categoryNameSales: 'Տուփ',
        productimg: 'https://abio.am/image/cache/catalog/picnic/picnicset_1-270x316.jpg',
        price: 3500,
        productName: 'Աքսեսուար Ճամպրուկով BBQ-Ի',
        zexcher: '25%',
        quantity: 1
    },
    {
        id: 44,
        categoryType: 'Զեղչեր',
        categoryTypeSales: 'Զեղչեր',
        categoryName: 'Տուփ',
        categoryNameSales: 'Տուփ',
        productimg: 'https://abio.am/image/cache/catalog/picnic/picnicset_1-270x316.jpg',
        price: 3500,
        productName: 'Աքսեսուար Ճամպրուկով BBQ-Ի',
        zexcher: '25%',
        quantity: 1
    },
    {
        id: 45,
        categoryType: 'Զեղչեր',
        categoryTypeSales: 'Զեղչեր',
        categoryName: 'Տուփ',
        categoryNameSales: 'Տուփ',
        productimg: 'https://abio.am/image/cache/catalog/picnic/picnicset_1-270x316.jpg',
        price: 3500,
        productName: 'Աքսեսուար Ճամպրուկով BBQ-Ի',
        zexcher: '25%',
        quantity: 1
    },
    // {
    //     id: 31,
    //     categoryType: 'Կահույք և դեկոր',
    //     categoryName: 'Ամանորյա դեկոր',
    //     productimg: 'https://mediamag.am/wp-content/uploads/2016/01/ciklamen_uhod.jpg',
    //     productPrice: '4,800',
    //     productName: 'Դիֆենբախիա կոմպակտ 2',
    //     zexcher: 'Զեղչեր'
    // },
    // {
    //     id: 32,
    //     categoryType: 'Պիկնիկի համար',
    //     categoryName: 'Պիկնիկի պարագաներ',
    //     productimg: 'https://mediamag.am/wp-content/uploads/2016/01/ciklamen_uhod.jpg',
    //     productPrice: '4,800',
    //     productName: 'Դիֆենբախիա կոմպակտ 2',
    //     zexcher: 'Զեղչեր'
    // },
    // {
    //     id: 33,
    //     categoryType: 'Պիկնիկի համար',
    //     categoryName: 'Տուփ',
    //     productimg: 'https://mediamag.am/wp-content/uploads/2016/01/ciklamen_uhod.jpg',
    //     productPrice: '4,800',
    //     productName: 'Դիֆենբախիա կոմպակտ 2',
    //     zexcher: 'Զեղչեր'
    // },
    // {
    //     id: 34,
    //     categoryType: 'Պիկնիկի համար',
    //     categoryName: 'Տուփ',
    //     productimg: 'https://mediamag.am/wp-content/uploads/2016/01/ciklamen_uhod.jpg',
    //     productPrice: '4,800',
    //     productName: 'Աիֆենբախիա կոմպակտ 2',
    //     zexcher: 'Զեղչեր'
    // },
]